name: VUE-CI

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

defaults:
  run:
    working-directory: actions-test

jobs:
  upload_to_aws_s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: upload to aws s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        run: aws s3 cp dist s3://vue-super-front --recursive
